export const ADMIN_EVENTS_LOADING    = 'admin/events/LOADING';
export const ADMIN_EVENTS_SUCCEEDED  = 'admin/events/SUCCEEDED';
export const ADMIN_EVENTS_FAILED     = 'admin/events/FAILED';

export const ADMIN_EVENTS_INSTANCE_ADDING = 'ADMIN_EVENTS_INSTANCE_ADDING';
export const ADMIN_EVENTS_INSTANCE_ADDED  = 'ADMIN_EVENTS_INSTANCE_ADDED';
export const ADMIN_EVENTS_INSTANCE_FAILED = 'ADMIN_EVENTS_INSTANCE_FAILED';

export const ADMIN_EVENTS_KEYS_LOADING   = "ADMIN_EVENTS_KEYS_LOADING";
export const ADMIN_EVENTS_KEYS_SUCCEEDED = "ADMIN_EVENTS_KEYS_SUCCEEDED";
export const ADMIN_EVENTS_KEYS_FAILED    = "ADMIN_EVENTS_KEYS_FAILED";
