version: '3'
services:
  database:
    build: ./database 
    ports:
      - "1433"
    volumes:
      - db:/var/opt/mssql
    env_file:
      - database.env
  client:
    build: ./client 
    ports:
      - "80"
    volumes:
      - .:/code
    env_file:
      - client.env
  server:
    build: ./server
    ports:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    env_file:
      - server.env
volumes:
  db: {}
