export const PLAYER_CLUES_FETCHING = 'PLAYER_CLUES_FETCHING';
export const PLAYER_CLUES_FETCHED  = 'PLAYER_CLUES_FETCHED';
export const PLAYER_CLUES_FAILED   = 'PLAYER_CLUES_FAILED';

export const PLAYER_CLUES_ANSWER_SUBMITTING = 'PLAYER_CLUES_ANSWER_SUBMITTING';
export const PLAYER_CLUES_ANSWER_SUBMITTED  = 'PLAYER_CLUES_ANSWER_SUBMITTED';
export const PLAYER_CLUES_ANSWER_FAILED     = 'PLAYER_CLUES_ANSWER_FAILED';

export const PLAYER_CLUES_RATING_SUBMITTING = 'PLAYER_CLUES_RATING_SUBMITTING';
export const PLAYER_CLUES_RATING_SUBMITTED  = 'PLAYER_CLUES_RATING_SUBMITTED';
export const PLAYER_CLUES_RATING_FAILED     = 'PLAYER_CLUES_RATING_FAILED';
