export const STAFF_TEAMS_FETCHING = 'STAFF_TEAMS_FETCHING';
export const STAFF_TEAMS_FETCHED  = 'STAFF_TEAMS_FETCHED';
export const STAFF_TEAMS_FAILED   = 'STAFF_TEAMS_FAILED';

export const STAFF_TEAMS_ADDING   = 'STAFF_TEAMS_ADDING';
export const STAFF_TEAMS_ADDED    = 'STAFF_TEAMS_ADDED';

export const STAFF_TEAMS_CALL_START   = 'STAFF_TEAMS_CALL_START';
export const STAFF_TEAMS_CALL_STARTED = 'STAFF_TEAMS_CALL_STARTED'
export const STAFF_TEAMS_CALL_FAILED = 'STAFF_TEAMS_CALL_FAILED';

export const STAFF_TEAMS_POINTS_GRANTING = "STAFF_TEAMS_POINTS_GRANTING";

export const STAFF_TEAMS_DATA_UPDATING = 'STAFF_TEAMS_DATA_UPDATING';
export const STAFF_TEAMS_DATA_UPDATED  = 'STAFF_TEAMS_DATA_UPDATED';
export const STAFF_TEAMS_DATA_FAILED   = 'STAFF_TEAMS_DATA_FAILED';
