export const USER_LOGIN_STARTED  = 'USER_LOGIN_STARTED';
export const USER_LOGIN_FINISHED = 'USER_LOGIN_FINISHED';
export const USER_LOGIN_FAILED   = 'USER_LOGIN_FAILED';

export const USER_LOGGED_OUT = "USER_LOGGED_OUT";