export const STAFF_ACHIEVEMENTS_FETCHING = 'staff/achievements/STAFF_ACHIEVEMENTS_FETCHING';
export const STAFF_ACHIEVEMENTS_FETCHED  = 'staff/achievements/STAFF_ACHIEVEMENTS_FETCHED';
export const STAFF_ACHIEVEMENTS_FAILED   = 'staff/achievements/STAFF_ACHIEVEMENTS_FAILED';

export const STAFF_ACHIEVEMENTS_ADDING     = 'staff/achievements/STAFF_ACHIEVEMENTS_ADDING';
export const STAFF_ACHIEVEMENTS_ADDED      = 'staff/achievements/STAFF_ACHIEVEMENTS_ADDED';
export const STAFF_ACHIEVEMENTS_ADD_FAILED = 'staff/achievements/STAFF_ACHIEVEMENTS_ADD_FAILED';

export const STAFF_ACHIEVEMENTS_TEAMS_LOADING   = 'staff/achievements/teams/STAFF_ACHIEVEMENTS_TEAMS_LOADING';
export const STAFF_ACHIEVEMENTS_TEAMS_SUCCEEDED = 'staff/achievements/teams/STAFF_ACHIEVEMENTS_TEAMS_SUCCEEDED';
export const STAFF_ACHIEVEMENTS_TEAMS_FAILED    = 'staff/achievements/teams/STAFF_ACHIEVEMENTS_TEAMS_FAILED';

export const STAFF_ACHIEVEMENTS_GRANT_FETCHING = 'staff/achievements/STAFF_ACHIEVEMENTS_GRANT_FETCHING';
export const STAFF_ACHIEVEMENTS_GRANT_FETCHED  = 'staff/achievements/STAFF_ACHIEVEMENTS_GRANT_FETCHED';
export const STAFF_ACHIEVEMENTS_GRANT_FAILED   = 'staff/achievements/STAFF_ACHIEVEMENTS_GRANT_FAILED';