export const PLAYER_ACHIEVEMENTS_FETCHING = 'player/achievements/PLAYER_ACHIEVEMENTS_FETCHING';
export const PLAYER_ACHIEVEMENTS_FETCHED  = 'player/achievements/PLAYER_ACHIEVEMENTS_FETCHED';
export const PLAYER_ACHIEVEMENTS_FAILED   = 'player/achievements/PLAYER_ACHIEVEMENTS_FAILED';