export const ADMIN_USERS_FETCHING  = 'ADMIN_USERS_FETCHING';
export const ADMIN_USERS_FETCHED   = 'ADMIN_USERS_FETCHED';
export const ADMIN_USERS_FAILED    = 'ADMIN_USERS_FAILED';

export const ADMIN_USER_UPDATEINFO_STARTED  = 'ADMIN_USER_UPDATEINFO_STARTED';
export const ADMIN_USER_UPDATEINFO_FINISHED = 'ADMIN_USER_UPDATEINFO_FINISHED';
export const ADMIN_USER_UPDATEINFO_FAILED   = 'ADMIN_USER_UPDATEINFO_FAILED';

export const ADMIN_USER_ADDTOEVENT_STARTED  = 'ADMIN_USER_ADDTOEVENT_STARTED';
export const ADMIN_USER_ADDTOEVENT_FINISHED = 'ADMIN_USER_ADDTOEVENT_FINISHED';
export const ADMIN_USER_ADDTOEVENT_FAILED   = 'ADMIN_USER_ADDTOEVENT_FAILED';