export const ADMIN_PLAYER_SUBMISSION_DELETING = "ADMIN_PLAYER_SUBMISSION_DELETING";
export const ADMIN_PLAYER_SUBMISSION_DELETED  = "ADMIN_PLAYER_SUBMISSION_DELETED";
export const ADMIN_PLAYER_SUBMISSION_FAILED   = "ADMIN_PLAYER_SUBMISSION_FAILED";