
export const PLAYER_CHALLENGES_FETCHING     = 'player/challenges/PLAYER_CHALLENGES_FETCHING';
export const PLAYER_CHALLENGES_FETCHED      = 'player/challenges/PLAYER_CHALLENGES_FETCHED';
export const PLAYER_CHALLENGES_FETCH_FAILED = 'player/challenges/PLAYER_CHALLENGES_FETCH_FAILED';

export const PLAYER_CHALLENGES_SUBS_FETCHING     = 'player/challenges/PLAYER_CHALLENGES_SUBS_FETCHING';
export const PLAYER_CHALLENGES_SUBS_FETCHED      = 'player/challenges/PLAYER_CHALLENGES_SUBS_FETCHED';
export const PLAYER_CHALLENGES_SUBS_FETCH_FAILED = 'player/challenges/PLAYER_CHALLENGES_SUBS_FETCH_FAILED';