CREATE LOGIN !!!GCUSERNAME!!!
    WITH PASSWORD = '!!!GCPASSWORD!!!';
CREATE LOGIN !!!PGUSERNAME!!!
    WITH PASSWORD = '!!!PGPASSWORD!!!';
USE [gamecontrol]
GO
CREATE USER !!!GCUSERNAME!!! FOR LOGIN !!!GCUSERNAME!!!
    WITH DEFAULT_SCHEMA = [dbo];
GO
ALTER ROLE db_datareader ADD MEMBER !!!GCUSERNAME!!!
GO
ALTER ROLE db_datawriter ADD MEMBER !!!GCUSERNAME!!!
GO
GRANT EXECUTE TO !!!GCUSERNAME!!!;
GO

USE [pregame]
GO
CREATE USER !!!PGUSERNAME!!! FOR LOGIN !!!PGUSERNAME!!!
    WITH DEFAULT_SCHEMA = [dbo];
GO  
ALTER ROLE db_datareader ADD MEMBER !!!PGUSERNAME!!!
GO
ALTER ROLE db_datawriter ADD MEMBER !!!PGUSERNAME!!!
GO
ALTER ROLE db_owner ADD MEMBER !!!PGUSERNAME!!!
GRANT EXECUTE TO !!!PGUSERNAME!!!;
GO
