USE [master]
GO
/****** Object: Database [pregame] ******/
CREATE DATABASE [pregame]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [pregame] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pregame].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [pregame] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [pregame] SET ANSI_NULLS OFF
GO
ALTER DATABASE [pregame] SET ANSI_PADDING OFF
GO
ALTER DATABASE [pregame] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [pregame] SET ARITHABORT OFF
GO
ALTER DATABASE [pregame] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [pregame] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [pregame] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [pregame] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [pregame] SET CURSOR_DEFAULT GLOBAL
GO
ALTER DATABASE [pregame] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [pregame] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [pregame] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [pregame] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [pregame] SET  ENABLE_BROKER
GO
ALTER DATABASE [pregame] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [pregame] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [pregame] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [pregame] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
ALTER DATABASE [pregame] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [pregame] SET READ_COMMITTED_SNAPSHOT ON
GO
ALTER DATABASE [pregame] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [pregame] SET RECOVERY FULL
GO
ALTER DATABASE [pregame] SET MULTI_USER
GO
ALTER DATABASE [pregame] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [pregame] SET DB_CHAINING OFF
GO
ALTER DATABASE [pregame] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [pregame] SET TARGET_RECOVERY_TIME = 120 SECONDS
GO
ALTER DATABASE [pregame] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [pregame] SET QUERY_STORE = ON
GO
ALTER DATABASE [pregame] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [pregame]
GO
