export const STAFF_CHALLENGES_FETCHING = "STAFF_CHALLENGES_FETCHING"
export const STAFF_CHALLENGES_FETCHED  = "STAFF_CHALLENGES_FETCHED";
export const STAFF_CHALLENGES_FAILED   = "STAFF_CHALLENGES_FAILED";

export const STAFF_CHALLENGES_ADDING     = "STAFF_CHALLENGES_ADDING";
export const STAFF_CHALLENGES_ADDED      = "STAFF_CHALLENGES_ADDED";
export const STAFF_CHALLENGES_ADD_FAILED = "STAFF_CHALLENGES_ADD_FAILED";