# This pipeline demonstrates how to build directly in a Windows VM
name: GameControlBuild
trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: MicrosoftInternGame-1ESPT-HostedPool
      image: MicrosoftInternGame-1ESPTImage-Linux
      os: linux
    sdl:
      baseline:
        baselineFile: $(Build.SourcesDirectory)\guardian\SDL\.gdnbaselines
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\guardian\SDL\.gdnsuppress
      sourceAnalysisPool:
        name: MicrosoftInternGame-1ESPT-HostedPool  # Name of your hosted pool
        image: MicrosoftInternGame-1ESPTImage  # Name of the image in your pool. If not specified, first image of the pool is used
        os: windows  # OS of the image. Allowed values: windows, linux, macOS
    stages:
    - stage: stage
      displayName: Build
      jobs:
      - job: client
        displayName: Build Spiderdog Client
        steps:
        # npm v1
        # Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
        - task: Npm@1
          displayName: 'npm ci'
          inputs:
            command: 'custom'
            workingDir: $(Build.SourcesDirectory)/client
            customCommand: 'ci --legacy-peer-deps'
            customRegistry: $(Build.SourcesDirectory)/.pipelines/.npmrc
        - task: Npm@1
          displayName: 'npm run build'
          inputs:
            command: 'custom'
            workingDir: $(Build.SourcesDirectory)/client
            customCommand: 'run build'
            customRegistry: $(Build.SourcesDirectory)/.pipelines/.npmrc
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Microsoft Intern Game(61f6dc5a-d24e-44f7-9c93-be9307ee3602)'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $subscriptionId = az account show | ConvertFrom-Json | Select-Object -ExpandProperty id;           
              $apiKey = az rest --method post --uri /subscriptions/$subscriptionId/resourceGroups/igshared/providers/Microsoft.Web/staticSites/spiderdoggo2/listSecrets?api-version=2019-08-01 | ConvertFrom-Json | Select-Object -ExpandProperty properties | Select-Object -ExpandProperty apiKey;             
              Write-Host "##vso[task.setvariable variable=webapptoken;issecret=true]$apiKey"

        - task: AzureStaticWebApp@0
          inputs:
            app_location: '/client/build/'
            skip_app_build: true
            skip_api_build: true
            verbose: true
            azure_static_web_apps_api_token: '$(webapptoken)'
            
      - job: server
        displayName: Build Spiderdog Server
        steps:
        - task: NuGetAuthenticate@1
          displayName: 'NuGet Authenticate'
        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: 'restore' # 'build' | 'push' | 'pack' | 'publish' | 'restore' | 'run' | 'test' | 'custom'. Required. Command. Default: build.
            projects: $(Build.SourcesDirectory)/server/GameControl.Server.sln
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            command: 'build' # 'build' | 'push' | 'pack' | 'publish' | 'restore' | 'run' | 'test' | 'custom'. Required. Command. Default: build.
            projects: $(Build.SourcesDirectory)/server/GameControl.Server.sln