# This pipeline demonstrates how to build directly in a Windows VM
name: GameControlBuild
trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: MicrosoftInternGame-1ESPT-HostedPool
      image: MicrosoftInternGame-1ESPTImage-Linux
      os: linux
    sdl:
      baseline:
        baselineFile: $(Build.SourcesDirectory)\guardian\SDL\.gdnbaselines
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\guardian\SDL\.gdnsuppress
      sourceAnalysisPool:
        name: MicrosoftInternGame-1ESPT-HostedPool  # Name of your hosted pool
        image: MicrosoftInternGame-1ESPTImage  # Name of the image in your pool. If not specified, first image of the pool is used
        os: windows  # OS of the image. Allowed values: windows, linux, macOS
    stages:
    - stage: stage
      displayName: Build
      jobs:
      - job: client
        displayName: Build Spiderdog Client
        steps:
        # npm v1
        # Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
        - task: Npm@1
          displayName: 'npm ci'
          inputs:
            command: 'custom'
            workingDir: $(Build.SourcesDirectory)/client
            customCommand: 'ci --legacy-peer-deps'
            customRegistry: $(Build.SourcesDirectory)/.pipelines/.npmrc
        - task: Npm@1
          displayName: 'npm run build'
          inputs:
            command: 'custom'
            workingDir: $(Build.SourcesDirectory)/client
            customCommand: 'run build'
            customRegistry: $(Build.SourcesDirectory)/.pipelines/.npmrc

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Microsoft Intern Game(61f6dc5a-d24e-44f7-9c93-be9307ee3602)'
            appType: 'webAppLinux'
            WebAppName: 'spiderdoggo2'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
            
      - job: server
        displayName: Build Spiderdog Server
        steps:
        - task: NuGetAuthenticate@1
          displayName: 'NuGet Authenticate'
        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: 'restore' # 'build' | 'push' | 'pack' | 'publish' | 'restore' | 'run' | 'test' | 'custom'. Required. Command. Default: build.
            projects: $(Build.SourcesDirectory)/server/GameControl.Server.sln
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            command: 'build' # 'build' | 'push' | 'pack' | 'publish' | 'restore' | 'run' | 'test' | 'custom'. Required. Command. Default: build.
            projects: $(Build.SourcesDirectory)/server/GameControl.Server.sln