export const STAFF_PUZZLES_UPDATE_ANSWER_LOADING = 'staff/puzzles/UPDATE_ANSWER_LOADING';
export const STAFF_PUZZLES_UPDATE_ANSWER_SUCCEEDED = 'staff/puzzles/UPDATE_ANSWER_SUCCEEDED';
export const STAFF_PUZZLES_UPDATE_ANSWER_FAILED = 'staff/puzzles/UPDATE_ANSWER_FAILED';

export const STAFF_PUZZLES_UNLOCKING = 'staff/puzzles/STAFF_PUZZLES_UNLOCKING';
export const STAFF_PUZZLES_UNLOCKED = 'staff/puzzles/STAFF_PUZZLES_UNLOCKED';
export const STAFF_PUZZLES_UNLOCK_FAILED = 'staff/puzzles/STAFF_PUZZLES_UNLOCK_FAILED';

export const ADD_INSTANCE_STARTED = 'staff/puzzles/ADD_INSTANCE_STARTED';
export const ADD_INSTANCE_FINISHED = 'staff/puzzles/ADD_INSTANCE_FINISHED';
export const ADD_INSTANCE_FAILED = 'staff/puzzles/ADD_INSTANCE_FAILED';

export const DELETE_INSTANCE_STARTED = 'staff/puzzles/DELETE_INSTANCE_STARTED';
export const DELETE_INSTANCE_FINISHED = 'staff/puzzles/DELETE_INSTANCE_FINISHED';
export const DELETE_INSTANCE_FAILED = 'staff/puzzles/DELETE_INSTANCE_FAILED';

export const STAFFCLUES_FETCHING = 'STAFFCLUES_FETCHING';
export const STAFFCLUES_FETCHED = 'STAFFCLUES_FETCHED';
export const STAFFCLUES_FAILED = 'STAFFCLUES_FAILED';
export const STAFFCLUES_ADDED = 'STAFFCLUES_ADDED';

export const ADD_ANSWER_STARTED = 'ADD_ANSWER_STARTED';
export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED';
export const ADD_ANSWER_FINISHED = 'ADD_ANSWER_FINISHED';

export const STAFFDETAILS_FETCHING = 'STAFFDETAILS_FETCHING';
export const STAFFDETAILS_FETCHED = 'STAFFDETAILS_FETCHED';
export const STAFFDETAILS_FAILED = 'STAFFDETAILS_FAILED';

// TODO: Can create and update be used together? What will that mean for
// the reducer?
export const STAFFCREATECLUE_PUTTING = 'STAFFCREATECLUE_PUTTING';
export const STAFFCREATECLUE_FETCHED = 'STAFFCREATECLUE_FETCHED';
export const STAFFCREATECLUE_FAILED = 'STAFFCREATECLUE_FAILED';
