export const STAFF_PUZZLES_UPDATE_ANSWER_LOADING = "staff/puzzles/UPDATE_ANSWER_LOADING";
export const STAFF_PUZZLES_UPDATE_ANSWER_SUCCEEDED = "staff/puzzles/UPDATE_ANSWER_SUCCEEDED";
export const STAFF_PUZZLES_UPDATE_ANSWER_FAILED = "staff/puzzles/UPDATE_ANSWER_FAILED";

export const STAFF_PUZZLES_UNLOCKING     = 'staff/puzzles/STAFF_PUZZLES_UNLOCKING';
export const STAFF_PUZZLES_UNLOCKED      = 'staff/puzzles/STAFF_PUZZLES_UNLOCKED'
export const STAFF_PUZZLES_UNLOCK_FAILED = 'staff/puzzles/STAFF_PUZZLES_UNLOCK_FAILED'

export const ADD_INSTANCE_STARTED  = "staff/puzzles/ADD_INSTANCE_STARTED";
export const ADD_INSTANCE_FINISHED = "staff/puzzles/ADD_INSTANCE_FINISHED";
export const ADD_INSTANCE_FAILED   = "staff/puzzles/ADD_INSTANCE_FAILED";

export const DELETE_INSTANCE_STARTED  = "staff/puzzles/DELETE_INSTANCE_STARTED";
export const DELETE_INSTANCE_FINISHED = "staff/puzzles/DELETE_INSTANCE_FINISHED";
export const DELETE_INSTANCE_FAILED   = "staff/puzzles/DELETE_INSTANCE_FAILED";